CREATE TYPE "ExperienceDetailType" AS ENUM ('RESPONSIBILITY', 'ACHIEVEMENT');
CREATE TYPE "MediaKind" AS ENUM ('IMAGE', 'DOCUMENT', 'ICON', 'OTHER');

ALTER TABLE "Achievement" ADD COLUMN "label" TEXT, ADD COLUMN "prefix" TEXT, ADD COLUMN "suffix" TEXT, ADD COLUMN "value" TEXT;
ALTER TABLE "Certification" ADD COLUMN "certificateFileUrl" TEXT, ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Experience" ADD COLUMN "employmentType" TEXT, ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "systems" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "technologies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Profile" ADD COLUMN "availabilityActive" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "availabilityText" TEXT, ADD COLUMN "heroDescription" TEXT, ADD COLUMN "heroImageUrl" TEXT, ADD COLUMN "mainTitle" TEXT, ADD COLUMN "primaryCtaText" TEXT, ADD COLUMN "primaryCtaUrl" TEXT, ADD COLUMN "professionalSummary" TEXT, ADD COLUMN "secondaryCtaText" TEXT, ADD COLUMN "secondaryCtaUrl" TEXT, ADD COLUMN "websiteUrl" TEXT;
ALTER TABLE "Project" ADD COLUMN "features" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "githubUrl" TEXT, ADD COLUMN "problem" TEXT, ADD COLUMN "results" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "role" TEXT, ADD COLUMN "solution" TEXT;
ALTER TABLE "Skill" ADD COLUMN "evidence" TEXT, ADD COLUMN "iconUrl" TEXT, ADD COLUMN "skillGroupId" TEXT, ALTER COLUMN "proficiency" DROP NOT NULL, ALTER COLUMN "proficiency" DROP DEFAULT;

CREATE TABLE "ProfileTitle" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "title" TEXT NOT NULL, "isPrimary" BOOLEAN NOT NULL DEFAULT false, "isActive" BOOLEAN NOT NULL DEFAULT true, "order" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProfileTitle_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AboutContent" ("id" TEXT NOT NULL, "sectionTitle" TEXT NOT NULL DEFAULT 'About Me', "subtitle" TEXT, "introduction" TEXT, "professionalSummary" TEXT, "mission" TEXT, "ctaText" TEXT, "ctaUrl" TEXT, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AboutContent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AboutPoint" ("id" TEXT NOT NULL, "aboutId" TEXT NOT NULL, "text" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AboutPoint_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExperienceDetail" ("id" TEXT NOT NULL, "experienceId" TEXT NOT NULL, "type" "ExperienceDetailType" NOT NULL, "text" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ExperienceDetail_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SkillGroup" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "order" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SkillGroup_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProjectImage" ("id" TEXT NOT NULL, "projectId" TEXT NOT NULL, "url" TEXT NOT NULL, "altText" TEXT, "isFeatured" BOOLEAN NOT NULL DEFAULT false, "order" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProjectImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProjectTechnology" ("projectId" TEXT NOT NULL, "skillId" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "ProjectTechnology_pkey" PRIMARY KEY ("projectId","skillId"));
CREATE TABLE "Service" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "icon" TEXT, "iconUrl" TEXT, "order" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Service_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SocialLink" ("id" TEXT NOT NULL, "platform" TEXT NOT NULL, "url" TEXT NOT NULL, "icon" TEXT, "order" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SocialLink_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NavigationItem" ("id" TEXT NOT NULL, "label" TEXT NOT NULL, "url" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "isVisible" BOOLEAN NOT NULL DEFAULT true, "newTab" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NavigationItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ContactContent" ("id" TEXT NOT NULL, "heading" TEXT NOT NULL DEFAULT 'Let''s Work Together', "description" TEXT, "email" TEXT, "phone" TEXT, "location" TEXT, "ctaText" TEXT, "ctaUrl" TEXT, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ContactContent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SeoSettings" ("id" TEXT NOT NULL, "siteTitle" TEXT NOT NULL, "metaDescription" TEXT NOT NULL, "keywords" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "openGraphTitle" TEXT, "openGraphDescription" TEXT, "openGraphImage" TEXT, "faviconUrl" TEXT, "canonicalUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SeoSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MediaAsset" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "url" TEXT NOT NULL, "kind" "MediaKind" NOT NULL, "mimeType" TEXT, "size" INTEGER, "altText" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MediaAsset_pkey" PRIMARY KEY ("id"));

CREATE INDEX "ProfileTitle_profileId_order_idx" ON "ProfileTitle"("profileId", "order"); CREATE INDEX "AboutPoint_aboutId_order_idx" ON "AboutPoint"("aboutId", "order"); CREATE INDEX "ExperienceDetail_experienceId_type_order_idx" ON "ExperienceDetail"("experienceId", "type", "order"); CREATE UNIQUE INDEX "SkillGroup_name_key" ON "SkillGroup"("name"); CREATE INDEX "SkillGroup_order_idx" ON "SkillGroup"("order"); CREATE INDEX "ProjectImage_projectId_order_idx" ON "ProjectImage"("projectId", "order"); CREATE INDEX "ProjectTechnology_projectId_order_idx" ON "ProjectTechnology"("projectId", "order"); CREATE INDEX "Service_order_idx" ON "Service"("order"); CREATE INDEX "SocialLink_order_idx" ON "SocialLink"("order"); CREATE INDEX "NavigationItem_order_idx" ON "NavigationItem"("order"); CREATE INDEX "MediaAsset_kind_idx" ON "MediaAsset"("kind"); CREATE INDEX "MediaAsset_createdAt_idx" ON "MediaAsset"("createdAt");

ALTER TABLE "ProfileTitle" ADD CONSTRAINT "ProfileTitle_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AboutPoint" ADD CONSTRAINT "AboutPoint_aboutId_fkey" FOREIGN KEY ("aboutId") REFERENCES "AboutContent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExperienceDetail" ADD CONSTRAINT "ExperienceDetail_experienceId_fkey" FOREIGN KEY ("experienceId") REFERENCES "Experience"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Skill" ADD CONSTRAINT "Skill_skillGroupId_fkey" FOREIGN KEY ("skillGroupId") REFERENCES "SkillGroup"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProjectImage" ADD CONSTRAINT "ProjectImage_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectTechnology" ADD CONSTRAINT "ProjectTechnology_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectTechnology" ADD CONSTRAINT "ProjectTechnology_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE;
