import Link from 'next/link'
import { ExternalLink, Mail, MapPin, Phone } from 'lucide-react'
import type { SiteSectionSetting } from '@/lib/siteSections'
import { prisma } from '@/lib/prisma'

export async function Footer({ profile, items = [], socialLinks = [] }: { profile: any; sections?: SiteSectionSetting[]; items?: any[]; socialLinks?: any[] }) {
  if (!items.length) items = await prisma.navigationItem.findMany({ where: { isVisible: true }, orderBy: { order: 'asc' } }).catch(()=>[])
  if (!socialLinks.length) socialLinks = await prisma.socialLink.findMany({ where: { isActive: true }, orderBy: { order: 'asc' } }).catch(()=>[])
  const name=profile?.name || 'Portfolio'
  const initials=name.split(' ').map((part:string)=>part[0]).join('').slice(0,2).toUpperCase()
  return <footer className="border-t border-border bg-card/40"><div className="section-container py-12"><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3"><div><div className="mb-3 flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-lg bg-primary text-xs font-bold text-primary-foreground">{initials}</span><span className="font-display font-bold">{name}</span></div>{(profile?.professionalSummary||profile?.summary)&&<p className="line-clamp-4 text-sm leading-relaxed text-muted-foreground">{profile.professionalSummary||profile.summary}</p>}</div><div><h3 className="mb-4 text-sm font-semibold">Quick links</h3><ul className="space-y-2 text-sm text-muted-foreground">{items.map((item)=><li key={item.id}><Link href={item.url} target={item.newTab?'_blank':undefined} className="hover:text-primary">{item.label}</Link></li>)}</ul></div><div><h3 className="mb-4 text-sm font-semibold">Contact</h3><div className="space-y-2 text-sm text-muted-foreground">{profile?.email&&<a className="flex items-center gap-2 hover:text-primary" href={`mailto:${profile.email}`}><Mail className="h-4 w-4 text-primary"/>{profile.email}</a>}{profile?.phone&&<a className="flex items-center gap-2 hover:text-primary" href={`tel:${profile.phone}`}><Phone className="h-4 w-4 text-primary"/>{profile.phone}</a>}{profile?.location&&<p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary"/>{profile.location}</p>}<div className="flex flex-wrap gap-3 pt-2">{socialLinks.map((link)=><a key={link.id} href={link.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-primary"><ExternalLink className="h-3 w-3"/>{link.platform}</a>)}</div></div></div></div><div className="mt-8 flex flex-col justify-between gap-3 border-t border-border pt-6 text-xs text-muted-foreground sm:flex-row"><p>© {new Date().getFullYear()} {name}. All rights reserved.</p><Link href="/admin/login" className="opacity-50 hover:opacity-100">Admin</Link></div></div></footer>
}
